In [204]:
import pandas as pd

In [146]:

df=pd.read_csv(r"C:\Users\lenovo\Desktop\CP05_04_01\datasets/Fuentes_Consumo_Energia.csv", encoding="UTF-8")
df.head(3)
    

Entity Code  Year  Coal_Consumption_EJ  Gas_Consumption_EJ  \
0  Africa  NaN  1965             1.164586            0.034358   
1  Africa  NaN  1966             1.163240            0.038412   
2  Africa  NaN  1967             1.189050            0.037964   

   Geo_Biomass_Other_TWh  Hydro_Generation_TWh  Nuclear_Generation_TWh  \
0                    0.0             13.905635                     0.0   
1                    0.0             15.510004                     0.0   
2                    0.0             16.190636                     0.0   

   Solar_Generation_TWh  Wind_Generation_TWh  Oil_Consumption_EJ  
0                   0.0                  0.0            1.173241  
1                   0.0                  0.0            1.284154  
2                   0.0                  0.0            1.273799

In [7]:
df.shape

(5190, 11)

In [19]:
Colom= df["Entity"].value_counts()["Colombia"]
Mex= df["Entity"].value_counts()["Mexico"]
tupla=(Colom, Mex)
tupla



(55, 55)

In [64]:

    #Esta función debe eliminar las columnas 'Code' y 'Entity' y luego informar la cantidad de columnas
    #retornando ese valor en un dato de tipo entero
col= ["Code", "Entity"]
df1=df.drop(col, axis=1)
h=int(df1.shape[1])



9

In [57]:
def Ret_Pregunta02():
    df=pd.read_csv(r"C:\Users\lenovo\Desktop\CP05_04_01\datasets/Fuentes_Consumo_Energia.csv", encoding="UTF-8")
    col= ["Code", "Entity"]
    df1=df.drop(col, axis=1)
    cantcolum=df1.shape
    return df1, cantcolum

Esta función debe informar la cantidad de registros de la columna Year sin tener en cuenta aquellos con valores faltantes
    retornando ese valor en un dato de tipo entero.

In [155]:
df.shape

(5190, 11)

In [81]:
df.info()
print(df.isna().sum())
#No hay valores faltantes en la columna Year
Cant_Reg=df["Year"].count
Cant_Reg




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5190 entries, 0 to 5189
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Entity                  5190 non-null   object 
 1   Code                    4145 non-null   object 
 2   Year                    5190 non-null   int64  
 3   Coal_Consumption_EJ     5170 non-null   float64
 4   Gas_Consumption_EJ      5170 non-null   float64
 5   Geo_Biomass_Other_TWh   5115 non-null   float64
 6   Hydro_Generation_TWh    5170 non-null   float64
 7   Nuclear_Generation_TWh  5170 non-null   float64
 8   Solar_Generation_TWh    5170 non-null   float64
 9   Wind_Generation_TWh     5170 non-null   float64
 10  Oil_Consumption_EJ      5184 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 446.1+ KB
Entity                       0
Code                      1045
Year                         0
Coal_Consumption_EJ         20
Gas_Consumption_

<bound method Series.count of 0       1965
1       1966
2       1967
3       1968
4       1969
        ... 
5185    2015
5186    2016
5187    2017
5188    2018
5189    2019
Name: Year, Length: 5190, dtype: int64>

In [83]:

Cant_Reg=df["Year"].count()
Cant_Reg

5190

 Esta función debe informar el año de mayor generación de energía hídrica (Hydro_Generation_TWh)
    para la entidad 'Europe' retornando ese valor en un dato de tipo entero.
    '''

In [173]:
Europa=df[df["Entity"]=="Europe"]
Energia_Europa=Europa["Year"][Europa["Hydro_Generation_TWh"].idxmax()]
Energia_Europa

2013

In [180]:
import numpy as np


In [195]:
m1 = np.array([[0,0,0],[1,1,1],[2,2,2]])
print(n1)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [196]:
m2 = np.array([[3,3],[4,4],[5,5]])
print(n2)

[[3 3]
 [4 4]
 [5 5]]


In [197]:
m3 = np.array([[1,1],[2,2]])
print(n3)

[[1 1]
 [2 2]]


In [198]:
def Ret_Pregunta06():
    if (m1.shape[1] == m2.shape[0] and m2.shape[1] == m3.shape[0]):
        return True
    else:
        return False

In [206]:
df=pd.read_csv(r"C:\Users\lenovo\Desktop\CP05_04_01\datasets/GGAL - Cotizaciones historicas.csv", encoding="UTF-8")
df.head(2)

especie       fecha  apertura   maximo   minimo   cierre  volumen  timestamp
0    GGAL  02/01/1991   0.02338  0.02338  0.02313  0.02338        0  662781600
1    GGAL  03/01/1991   0.02289  0.02289  0.02251  0.02289        0  662868000

In [217]:
#Esta función debe tomar la columna máximo y 
#devolver la suma de los valores de esta, con 4 decimales después del punto, redondeado.
Suma=df["maximo"].sum()
round(Suma,4)

202185.8933